// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` only reads the schema -- it never opens a
    // connection -- so a missing DATABASE_URL (CI, or a build step
    // before env vars are injected) shouldn't block producing the
    // client. Runtime DB access still enforces a real DATABASE_URL
    // itself (see app/server/db/prisma.ts), and `migrate`/`db push`
    // will fail with a real connection error if this placeholder is
    // ever actually used.
    url: process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
